/**
 * 同城家教 API
 * 同城家教 接口文档, V1.0
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ChangePasswordRequest {
  
  @SerializedName("token")
  private String token = null;
  @SerializedName("oldpassword")
  private String oldpassword = null;
  @SerializedName("password")
  private String password = null;
  @SerializedName("repassword")
  private String repassword = null;

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getOldpassword() {
    return oldpassword;
  }
  public void setOldpassword(String oldpassword) {
    this.oldpassword = oldpassword;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getRepassword() {
    return repassword;
  }
  public void setRepassword(String repassword) {
    this.repassword = repassword;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChangePasswordRequest changePasswordRequest = (ChangePasswordRequest) o;
    return (this.token == null ? changePasswordRequest.token == null : this.token.equals(changePasswordRequest.token)) &&
        (this.oldpassword == null ? changePasswordRequest.oldpassword == null : this.oldpassword.equals(changePasswordRequest.oldpassword)) &&
        (this.password == null ? changePasswordRequest.password == null : this.password.equals(changePasswordRequest.password)) &&
        (this.repassword == null ? changePasswordRequest.repassword == null : this.repassword.equals(changePasswordRequest.repassword));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    result = 31 * result + (this.oldpassword == null ? 0: this.oldpassword.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.repassword == null ? 0: this.repassword.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChangePasswordRequest {\n");
    
    sb.append("  token: ").append(token).append("\n");
    sb.append("  oldpassword: ").append(oldpassword).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  repassword: ").append(repassword).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
