/**
 * 同城家教 API
 * 同城家教 接口文档, V1.0
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class CheckVarcodeRequest {
  
  @SerializedName("mobile_num")
  private String mobileNum = null;
  @SerializedName("varcode")
  private String varcode = null;

  /**
   * mobile phone
   **/
  @ApiModelProperty(required = true, value = "mobile phone")
  public String getMobileNum() {
    return mobileNum;
  }
  public void setMobileNum(String mobileNum) {
    this.mobileNum = mobileNum;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getVarcode() {
    return varcode;
  }
  public void setVarcode(String varcode) {
    this.varcode = varcode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckVarcodeRequest checkVarcodeRequest = (CheckVarcodeRequest) o;
    return (this.mobileNum == null ? checkVarcodeRequest.mobileNum == null : this.mobileNum.equals(checkVarcodeRequest.mobileNum)) &&
        (this.varcode == null ? checkVarcodeRequest.varcode == null : this.varcode.equals(checkVarcodeRequest.varcode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mobileNum == null ? 0: this.mobileNum.hashCode());
    result = 31 * result + (this.varcode == null ? 0: this.varcode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckVarcodeRequest {\n");
    
    sb.append("  mobileNum: ").append(mobileNum).append("\n");
    sb.append("  varcode: ").append(varcode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
