/**
 * 同城家教 API
 * 同城家教 接口文档, V1.0
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GetPhoneVarcodeRequest {
  
  @SerializedName("mobile_num")
  private String mobileNum = null;
  @SerializedName("type")
  private Integer type = null;

  /**
   * mobile phone
   **/
  @ApiModelProperty(required = true, value = "mobile phone")
  public String getMobileNum() {
    return mobileNum;
  }
  public void setMobileNum(String mobileNum) {
    this.mobileNum = mobileNum;
  }

  /**
   * 1:register,2:forget password,3:bind phone
   **/
  @ApiModelProperty(required = true, value = "1:register,2:forget password,3:bind phone")
  public Integer getType() {
    return type;
  }
  public void setType(Integer type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPhoneVarcodeRequest getPhoneVarcodeRequest = (GetPhoneVarcodeRequest) o;
    return (this.mobileNum == null ? getPhoneVarcodeRequest.mobileNum == null : this.mobileNum.equals(getPhoneVarcodeRequest.mobileNum)) &&
        (this.type == null ? getPhoneVarcodeRequest.type == null : this.type.equals(getPhoneVarcodeRequest.type));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mobileNum == null ? 0: this.mobileNum.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPhoneVarcodeRequest {\n");
    
    sb.append("  mobileNum: ").append(mobileNum).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
