/**
 * 同城家教 API
 * 同城家教 接口文档, V1.0
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginModel {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("user_nicename")
  private String userNicename = null;
  @SerializedName("avatar")
  private String avatar = null;
  @SerializedName("sex")
  private String sex = null;
  @SerializedName("signature")
  private String signature = null;
  @SerializedName("user_status")
  private String userStatus = null;
  @SerializedName("token")
  private String token = null;

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getUserNicename() {
    return userNicename;
  }
  public void setUserNicename(String userNicename) {
    this.userNicename = userNicename;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getAvatar() {
    return avatar;
  }
  public void setAvatar(String avatar) {
    this.avatar = avatar;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getSex() {
    return sex;
  }
  public void setSex(String sex) {
    this.sex = sex;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getSignature() {
    return signature;
  }
  public void setSignature(String signature) {
    this.signature = signature;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getUserStatus() {
    return userStatus;
  }
  public void setUserStatus(String userStatus) {
    this.userStatus = userStatus;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginModel loginModel = (LoginModel) o;
    return (this.id == null ? loginModel.id == null : this.id.equals(loginModel.id)) &&
        (this.userNicename == null ? loginModel.userNicename == null : this.userNicename.equals(loginModel.userNicename)) &&
        (this.avatar == null ? loginModel.avatar == null : this.avatar.equals(loginModel.avatar)) &&
        (this.sex == null ? loginModel.sex == null : this.sex.equals(loginModel.sex)) &&
        (this.signature == null ? loginModel.signature == null : this.signature.equals(loginModel.signature)) &&
        (this.userStatus == null ? loginModel.userStatus == null : this.userStatus.equals(loginModel.userStatus)) &&
        (this.token == null ? loginModel.token == null : this.token.equals(loginModel.token));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.userNicename == null ? 0: this.userNicename.hashCode());
    result = 31 * result + (this.avatar == null ? 0: this.avatar.hashCode());
    result = 31 * result + (this.sex == null ? 0: this.sex.hashCode());
    result = 31 * result + (this.signature == null ? 0: this.signature.hashCode());
    result = 31 * result + (this.userStatus == null ? 0: this.userStatus.hashCode());
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginModel {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  userNicename: ").append(userNicename).append("\n");
    sb.append("  avatar: ").append(avatar).append("\n");
    sb.append("  sex: ").append(sex).append("\n");
    sb.append("  signature: ").append(signature).append("\n");
    sb.append("  userStatus: ").append(userStatus).append("\n");
    sb.append("  token: ").append(token).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
