/**
 * 同城家教 API
 * 同城家教 接口文档, V1.0
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginRequest {
  
  @SerializedName("mobile_num")
  private String mobileNum = null;
  @SerializedName("password")
  private String password = null;

  /**
   * mobile phone
   **/
  @ApiModelProperty(required = true, value = "mobile phone")
  public String getMobileNum() {
    return mobileNum;
  }
  public void setMobileNum(String mobileNum) {
    this.mobileNum = mobileNum;
  }

  /**
   * password
   **/
  @ApiModelProperty(required = true, value = "password")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginRequest loginRequest = (LoginRequest) o;
    return (this.mobileNum == null ? loginRequest.mobileNum == null : this.mobileNum.equals(loginRequest.mobileNum)) &&
        (this.password == null ? loginRequest.password == null : this.password.equals(loginRequest.password));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mobileNum == null ? 0: this.mobileNum.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginRequest {\n");
    
    sb.append("  mobileNum: ").append(mobileNum).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
