/**
 * 同城家教 API
 * 同城家教 接口文档, V1.0
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RegisterRequest {
  
  @SerializedName("mobile_num")
  private String mobileNum = null;
  @SerializedName("password")
  private String password = null;
  @SerializedName("varcode")
  private String varcode = null;
  @SerializedName("user_nicename")
  private String userNicename = null;
  @SerializedName("is_tutor")
  private Integer isTutor = null;
  @SerializedName("promote_code")
  private String promoteCode = null;

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getMobileNum() {
    return mobileNum;
  }
  public void setMobileNum(String mobileNum) {
    this.mobileNum = mobileNum;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getVarcode() {
    return varcode;
  }
  public void setVarcode(String varcode) {
    this.varcode = varcode;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getUserNicename() {
    return userNicename;
  }
  public void setUserNicename(String userNicename) {
    this.userNicename = userNicename;
  }

  /**
   * 0:student,1:teacher
   **/
  @ApiModelProperty(value = "0:student,1:teacher")
  public Integer getIsTutor() {
    return isTutor;
  }
  public void setIsTutor(Integer isTutor) {
    this.isTutor = isTutor;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getPromoteCode() {
    return promoteCode;
  }
  public void setPromoteCode(String promoteCode) {
    this.promoteCode = promoteCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegisterRequest registerRequest = (RegisterRequest) o;
    return (this.mobileNum == null ? registerRequest.mobileNum == null : this.mobileNum.equals(registerRequest.mobileNum)) &&
        (this.password == null ? registerRequest.password == null : this.password.equals(registerRequest.password)) &&
        (this.varcode == null ? registerRequest.varcode == null : this.varcode.equals(registerRequest.varcode)) &&
        (this.userNicename == null ? registerRequest.userNicename == null : this.userNicename.equals(registerRequest.userNicename)) &&
        (this.isTutor == null ? registerRequest.isTutor == null : this.isTutor.equals(registerRequest.isTutor)) &&
        (this.promoteCode == null ? registerRequest.promoteCode == null : this.promoteCode.equals(registerRequest.promoteCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mobileNum == null ? 0: this.mobileNum.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.varcode == null ? 0: this.varcode.hashCode());
    result = 31 * result + (this.userNicename == null ? 0: this.userNicename.hashCode());
    result = 31 * result + (this.isTutor == null ? 0: this.isTutor.hashCode());
    result = 31 * result + (this.promoteCode == null ? 0: this.promoteCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegisterRequest {\n");
    
    sb.append("  mobileNum: ").append(mobileNum).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  varcode: ").append(varcode).append("\n");
    sb.append("  userNicename: ").append(userNicename).append("\n");
    sb.append("  isTutor: ").append(isTutor).append("\n");
    sb.append("  promoteCode: ").append(promoteCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
