/**
 * 同城家教 API
 * 同城家教 接口文档, V1.0
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class RetrievePasswordRequest {
  
  @SerializedName("token")
  private String token = null;
  @SerializedName("varcode")
  private String varcode = null;
  @SerializedName("password")
  private String password = null;
  @SerializedName("repassword")
  private String repassword = null;

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getVarcode() {
    return varcode;
  }
  public void setVarcode(String varcode) {
    this.varcode = varcode;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getPassword() {
    return password;
  }
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * 
   **/
  @ApiModelProperty(required = true, value = "")
  public String getRepassword() {
    return repassword;
  }
  public void setRepassword(String repassword) {
    this.repassword = repassword;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetrievePasswordRequest retrievePasswordRequest = (RetrievePasswordRequest) o;
    return (this.token == null ? retrievePasswordRequest.token == null : this.token.equals(retrievePasswordRequest.token)) &&
        (this.varcode == null ? retrievePasswordRequest.varcode == null : this.varcode.equals(retrievePasswordRequest.varcode)) &&
        (this.password == null ? retrievePasswordRequest.password == null : this.password.equals(retrievePasswordRequest.password)) &&
        (this.repassword == null ? retrievePasswordRequest.repassword == null : this.repassword.equals(retrievePasswordRequest.repassword));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.token == null ? 0: this.token.hashCode());
    result = 31 * result + (this.varcode == null ? 0: this.varcode.hashCode());
    result = 31 * result + (this.password == null ? 0: this.password.hashCode());
    result = 31 * result + (this.repassword == null ? 0: this.repassword.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetrievePasswordRequest {\n");
    
    sb.append("  token: ").append(token).append("\n");
    sb.append("  varcode: ").append(varcode).append("\n");
    sb.append("  password: ").append(password).append("\n");
    sb.append("  repassword: ").append(repassword).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
